# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-github-repository-webhooks
  description: Terraform module to provision webhooks on a set of GitHub repositories
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-module, webhooks, github, jenkins, codebuild, atlantis, cicd, callbacks, hcl2
